"""
Configuration Package
"""
from src.config.model_config import (
    MODEL_PROVIDERS,
    DEFAULT_VISION_MODEL,
    FALLBACK_VISION_MODEL,
    EXPENSE_CATEGORIES,
    MIN_CONFIDENCE_SCORE,
    GOOD_CONFIDENCE_SCORE,
    EXCELLENT_CONFIDENCE_SCORE
)

from src.config.settings import (
    PROJECT_ROOT,
    DATABASE_PATH,
    UPLOAD_FOLDER,
    OUTPUT_FOLDER,
    DB_PATH,
    SUPPORTED_FORMATS,
    MAX_FILE_SIZE_MB,
    DEFAULT_USER_ID
)

__all__ = [
    'MODEL_PROVIDERS',
    'DEFAULT_VISION_MODEL',
    'FALLBACK_VISION_MODEL',
    'EXPENSE_CATEGORIES',
    'MIN_CONFIDENCE_SCORE',
    'GOOD_CONFIDENCE_SCORE',
    'EXCELLENT_CONFIDENCE_SCORE',
    'PROJECT_ROOT',
    'DATABASE_PATH',
    'UPLOAD_FOLDER',
    'OUTPUT_FOLDER',
    'DB_PATH',
    'SUPPORTED_FORMATS',
    'MAX_FILE_SIZE_MB',
    'DEFAULT_USER_ID'
]